//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{
    public partial class Bookings
    {
        protected global::System.Web.UI.WebControls.HiddenField hfBookingId;
        protected global::System.Web.UI.WebControls.TextBox txtBookingDate;
        protected global::System.Web.UI.WebControls.TextBox txtBookingStatus;
        protected global::System.Web.UI.WebControls.TextBox txtTotalAmount;
        protected global::System.Web.UI.WebControls.DropDownList ddlUser;
        protected global::System.Web.UI.WebControls.DropDownList ddlShow;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvBookings;
    }
}
