//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{


    public partial class _Default
    {
        /// <summary>
        /// lblUsersCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsersCount;

        /// <summary>
        /// lblMoviesCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMoviesCount;

        /// <summary>
        /// lblTheatersCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTheatersCount;

        /// <summary>
        /// lblShowsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblShowsCount;

        /// <summary>
        /// lblTicketsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTicketsCount;

        /// <summary>
        /// lblBookingsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBookingsCount;

        /// <summary>
        /// lblHallsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHallsCount;

        /// <summary>
        /// lblGeneratedAt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblGeneratedAt;
    }
}
