//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{
    public partial class Halls
    {
        protected global::System.Web.UI.WebControls.HiddenField hfHallId;
        protected global::System.Web.UI.WebControls.TextBox txtHallNumber;
        protected global::System.Web.UI.WebControls.TextBox txtSeatingCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtHallType;
        protected global::System.Web.UI.WebControls.TextBox txtHallStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlTheater;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvHalls;
    }
}
