//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{
    public partial class Movies
    {
        protected global::System.Web.UI.WebControls.HiddenField hfMovieId;
        protected global::System.Web.UI.WebControls.TextBox txtMovieTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDuration;
        protected global::System.Web.UI.WebControls.TextBox txtLanguage;
        protected global::System.Web.UI.WebControls.TextBox txtGenre;
        protected global::System.Web.UI.WebControls.TextBox txtReleaseDate;
        protected global::System.Web.UI.WebControls.Button btnInsert;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvMovies;
    }
}
