//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{
    public partial class Shows
    {
        protected global::System.Web.UI.WebControls.HiddenField hfShowId;
        protected global::System.Web.UI.WebControls.TextBox txtShowDate;
        protected global::System.Web.UI.WebControls.TextBox txtShowTime;
        protected global::System.Web.UI.WebControls.TextBox txtShowRating;
        protected global::System.Web.UI.WebControls.DropDownList ddlMovie;
        protected global::System.Web.UI.WebControls.DropDownList ddlHall;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvShows;
    }
}
