//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{
    public partial class Theaters
    {
        protected global::System.Web.UI.WebControls.HiddenField hfTheaterId;
        protected global::System.Web.UI.WebControls.TextBox txtTheaterName;
        protected global::System.Web.UI.WebControls.TextBox txtTheaterCity;
        protected global::System.Web.UI.WebControls.TextBox txtTheaterLocation;
        protected global::System.Web.UI.WebControls.TextBox txtTheaterContact;
        protected global::System.Web.UI.WebControls.TextBox txtTotalHalls;
        protected global::System.Web.UI.WebControls.Button btnInsert;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvTheaters;
    }
}
