//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{
    public partial class Tickets
    {
        protected global::System.Web.UI.WebControls.HiddenField hfTicketId;
        protected global::System.Web.UI.WebControls.TextBox txtSeatNumber;
        protected global::System.Web.UI.WebControls.TextBox txtTicketStatus;
        protected global::System.Web.UI.WebControls.TextBox txtTicketPrice;
        protected global::System.Web.UI.WebControls.DropDownList ddlBooking;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvTickets;
    }
}
