//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketSystem
{
    public partial class Users
    {
        protected global::System.Web.UI.WebControls.HiddenField hfUserId;
        protected global::System.Web.UI.WebControls.TextBox txtUserName;
        protected global::System.Web.UI.WebControls.TextBox txtUserEmail;
        protected global::System.Web.UI.WebControls.TextBox txtUserContact;
        protected global::System.Web.UI.WebControls.TextBox txtUserAddress;
        protected global::System.Web.UI.WebControls.TextBox txtRegistrationDate;
        protected global::System.Web.UI.WebControls.Button btnInsert;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
