BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE AppUser (
    User_Id NUMBER(10) PRIMARY KEY,
    User_Name VARCHAR2(100) NOT NULL,
    User_Email VARCHAR2(120) NOT NULL,
    User_Contact_Number VARCHAR2(20) NOT NULL,
    User_Address VARCHAR2(250) NOT NULL,
    User_Registration_Date DATE NOT NULL
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE Theater (
    Theater_Id NUMBER(10) PRIMARY KEY,
    Theater_Name VARCHAR2(120) NOT NULL,
    Theater_City VARCHAR2(60) NOT NULL,
    Theater_Location VARCHAR2(200) NOT NULL,
    Theater_Contact_Number VARCHAR2(20) NOT NULL,
    Theater_Total_Halls NUMBER(10) NOT NULL
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE Hall (
    Hall_Id NUMBER(10) PRIMARY KEY,
    Hall_Number VARCHAR2(20) NOT NULL,
    Hall_Seating_Capacity NUMBER(10) NOT NULL,
    Hall_Type VARCHAR2(50) NOT NULL,
    Hall_Status VARCHAR2(40) NOT NULL,
    Theater_Id NUMBER(10) NOT NULL,
    CONSTRAINT FK_Hall_Theater FOREIGN KEY (Theater_Id) REFERENCES Theater(Theater_Id) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE Movie (
    Movie_Id NUMBER(10) PRIMARY KEY,
    Movie_Title VARCHAR2(150) NOT NULL,
    Movie_Duration NUMBER(10) NOT NULL,
    Movie_Language VARCHAR2(50) NOT NULL,
    Movie_Genre VARCHAR2(50) NOT NULL,
    Movie_Release_Date DATE NOT NULL
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE Show (
    Show_Id NUMBER(10) PRIMARY KEY,
    Show_Date DATE NOT NULL,
    Show_Time VARCHAR2(5) NOT NULL,
    Show_Rating VARCHAR2(10) NOT NULL,
    Movie_Id NUMBER(10) NOT NULL,
    Hall_Id NUMBER(10) NOT NULL,
    CONSTRAINT FK_Show_Movie FOREIGN KEY (Movie_Id) REFERENCES Movie(Movie_Id) ON DELETE CASCADE,
    CONSTRAINT FK_Show_Hall FOREIGN KEY (Hall_Id) REFERENCES Hall(Hall_Id) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE Booking (
    Booking_Id NUMBER(10) PRIMARY KEY,
    Booking_Date DATE NOT NULL,
    Booking_Status VARCHAR2(30) NOT NULL,
    Total_Amount NUMBER(10,2) NOT NULL,
    User_Id NUMBER(10) NOT NULL,
    Show_Id NUMBER(10) NOT NULL,
    CONSTRAINT FK_Booking_AppUser FOREIGN KEY (User_Id) REFERENCES AppUser(User_Id) ON DELETE CASCADE,
    CONSTRAINT FK_Booking_Show FOREIGN KEY (Show_Id) REFERENCES Show(Show_Id) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE Ticket (
    Ticket_Id NUMBER(10) PRIMARY KEY,
    Seat_Number VARCHAR2(20) NOT NULL,
    Ticket_Status VARCHAR2(30) NOT NULL,
    Ticket_Price NUMBER(10,2) NOT NULL,
    Booking_Id NUMBER(10) NOT NULL,
    CONSTRAINT FK_Ticket_Booking FOREIGN KEY (Booking_Id) REFERENCES Booking(Booking_Id) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE APPUSER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE THEATER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE HALL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MOVIE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SHOW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE TICKET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER APPUSER_BI
BEFORE INSERT ON AppUser
FOR EACH ROW
BEGIN
  IF :NEW.User_Id IS NULL THEN
    SELECT APPUSER_SEQ.NEXTVAL INTO :NEW.User_Id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER THEATER_BI
BEFORE INSERT ON Theater
FOR EACH ROW
BEGIN
  IF :NEW.Theater_Id IS NULL THEN
    SELECT THEATER_SEQ.NEXTVAL INTO :NEW.Theater_Id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER HALL_BI
BEFORE INSERT ON Hall
FOR EACH ROW
BEGIN
  IF :NEW.Hall_Id IS NULL THEN
    SELECT HALL_SEQ.NEXTVAL INTO :NEW.Hall_Id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER MOVIE_BI
BEFORE INSERT ON Movie
FOR EACH ROW
BEGIN
  IF :NEW.Movie_Id IS NULL THEN
    SELECT MOVIE_SEQ.NEXTVAL INTO :NEW.Movie_Id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER SHOW_BI
BEFORE INSERT ON Show
FOR EACH ROW
BEGIN
  IF :NEW.Show_Id IS NULL THEN
    SELECT SHOW_SEQ.NEXTVAL INTO :NEW.Show_Id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER BOOKING_BI
BEFORE INSERT ON Booking
FOR EACH ROW
BEGIN
  IF :NEW.Booking_Id IS NULL THEN
    SELECT BOOKING_SEQ.NEXTVAL INTO :NEW.Booking_Id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TICKET_BI
BEFORE INSERT ON Ticket
FOR EACH ROW
BEGIN
  IF :NEW.Ticket_Id IS NULL THEN
    SELECT TICKET_SEQ.NEXTVAL INTO :NEW.Ticket_Id FROM dual;
  END IF;
END;
/
